### ISSUE TITLE
Unable to install the module

### ISSUE THREAD

**Issue by velizarn** [http-auth/http-auth-connect#1]
When I run _npm install http-auth-connect_ the module is installed without src directory and after I run my script an error message appears: _Error: Cannot find module 'http-auth-connect'_

**Comment by gevorg** [comment]
My bad, please re-check. I published new versions.

**Comment by velizarn** [comment]
src is installed correctly after 1.0.2 update however following error occurs after npm audit fix :

`npm ERR! code ELOCKVERIFY`
`npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.`
`npm ERR!     Invalid: lock file's http-auth-connect@1.0.2 does not satisfy http-auth-connect@1.0.1`

**Comment by gevorg** [comment]
try to remove node_modules and re-run install

**Comment by gevorg** [comment]
not related to package I think
